config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # read
  get 'tasks', to: 'tasks#index'
  # create
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  # details
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  # update
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'
  patch 'tasks/:id', to: 'tasks#update'
  # delete
  get 'tasks/:id/delete', to: 'tasks#destroy', as: 'delete'
  # mark as done
  post 'tasks/:id/mark', to: 'tasks#mark', as: 'mark'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :retrieve_task, only: [:show, :edit, :update, :destroy, :mark]
  def index
    @tasks = Task.all
  end

  def show; end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def new
    @task = Task.new
  end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark
    @task.completed = true
    @task.save
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def retrieve_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "col-md-4 control-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :details, class: "col-md-4 control-label" %>
    <%= f.text_field :details, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :completed, class: "col-md-4 control-label" %>
    <%= f.check_box :completed, type: "checkbox", class: "form-control"%>
  </div>

  <%= f.submit class: 'btn btn-primary'%>

<% end %>

app/views/tasks/edit.html.erb
<h1>Edit this task</h1>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>My Tasks</h1>
  <ul>
    <% @tasks.each do |task| %>
    <% check = task.completed == true ? "✅" : "❎" %>
    <li>
      <%= link_to check + " " + task.title, task_path(task[:id]), class: 'title' %>
      <div class="actions">
        <%= link_to "Destroy", delete_path(task), class: 'btn btn-danger' %>
        <%= link_to "Mark as done", mark_path(task), method: :post, class: 'btn btn-secondary' %>
      </div>

    </li>
    <% end %>
  </ul>

  <%= link_to "Create", tasks_new_path, class: 'btn btn-success' %>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create a new task</h1>

  <%= render 'form' %>

  <%= link_to "Back to Tasks", tasks_path, class: "btn btn-light mt-5" %>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <h1><%= @task.title %></h1>
  <h2><%= @task.details %></h2>
  <% message = @task.completed == true ? "✅ This task is completed" : "❎ This task is not completed"%>
  <h2><%= message %></h2>

  <%= link_to "Back to Tasks", tasks_path, class: "btn btn-light mt-5" %>
  <%= link_to "Edit", edit_path(@task), class: "btn btn-primary mt-5" %>
</div>